name: Python application

on:
  push:
    branches:
      - fixing
  pull_request:
    branches:
      - fixing

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.9 3.10 3.11

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install -r requirements.txt

    - name: Build package
      run: |
        python setup.py sdist bdist_wheel

    - name: Install package
      run: |
        pip install .

    - name: Run tests
      run: |
        pytest
